server:
  port: 8200


spring:
  redis:
    database: 0
    password:       # 密码（默认为空）
    timeout: 20000   # 连接超时时长（毫秒）
    jedis:
      pool:
        max-active: 200  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 16      # 连接池中的最大空闲连接
        min-idle: 8       # 连接池中的最小空闲连接
    sentinel:
      master: mymaster
      nodes:
      - redis-ha-test-announce-0:26379
      - redis-ha-test-announce-1:26379
      - redis-ha-test-announce-2:26379
  klock:
    address: redis://redis-ha-test-announce-0:26379,redis://redis-ha-test-announce-1:26379,redis://redis-ha-test-announce-2:26379
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@47.75.108.42:1521:hkmetro
    username: passengerdb2
    password: Pcidata321
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 10    # 初始化连接数
    min-idle: 10        # 最小空闲连接
    max-active: 100     # 最大活动链接
    max-wait: 60000     # 最大等待时间(毫秒)
    test-while-idle: true
    test-on-borrow: false # 获取连接时测试是否可用
    test-on-return: false
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    min-evictable-idle-time-millis: 300000
  session:
    store-type: redis
  resources:
    static-locations: ["/static/"]
  jackson:
    date-format: dd/MM/yy HH:mm:ss
    time-zone: GMT+8
  devtools:
    restart:
      #热部署生效
      enabled: false
  kafka:
    bootstrap-servers: 47.244.188.35:9092
    producer:
      retries: 0
      batch-size: 16384
      buffer-memory: 33554432
      linger: 1
    consumer:
      enable-auto-commit: false
      auto-commit-interval: 100
      group-id: passenger_group
      session-timeout: 20000
      auto-offset-reset: latest
      concurrency: 10

mybatis:
  type-aliases-package: com.mtr.sscp.entity
  mapper-locations: classpath:mapper/*.xml
#  驼峰命名规范，不加不能把tap_time映射为tapTime字段实体
  configuration:
    map-underscore-to-camel-case: true

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false

#logback:
#  #非开发环境是否开启控制台日志
#  enableConsoleLogWhenNotInDev: false
#  #**日志文件存放目录，目录后面无需再加"/"。备注如果这项不配置，则不输出日志文件
#  logFileDir: /fs01/log


#jdbc操作日志
log:
  jdbc:
    ps:
      executableSql: true
    rs:
      header: true

# /swagger-ui.html swagger访问网址
swagger:
  enable: true

#分布式id机器码      
snowflake:
  workerId: 0  #取值0-31
  datacenterId: 1  #取值0-31

parameters:
  mtrAuthorizationUrl: https://www.baidu.com 	#Mtr授权Url
