apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: example-app
  labels:
    team: frontend
spec:
  endpoints:
  - port: web
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      app: example-app
