apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  type: NodePort
  ports:
  - port: 8700
    targetPort: 8700
    nodePort: 30187
  selector:
    app: {{ .Values.app.name }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.app.tls }}
  tls:
  - hosts:
    - {{ .Values.app.host}}
    secretName: {{ .Values.app.tls}}
{{- end }}
  rules:
  - host: {{ .Values.app.host}}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.app.name }}
          servicePort: 8700
