server:
  port: 8600

spring:
  redis:  #redis配置
    database: 8
    host: redis-ha
    port: 6379
    password:
    timeout: 20000
    jedis:
      pool:
        max-active: 200  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms    # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10      # 连接池中的最大空闲连接
        min-idle: 5       # 连接池中的最小空闲连接
    sentinel:
      master: mymaster
      nodes:
      - redis-ha-announce-0:26379
      - redis-ha-announce-1:26379
      - redis-ha-announce-2:26379
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@47.244.5.51:1521:xe
    username: notificationdb
    password: pcidata_2019
    type: com.alibaba.druid.pool.DruidDataSource
    initial-size: 10    # 初始化连接数
    min-idle: 10        # 最小空闲连接
    max-active: 100     # 最大活动链接
    max-wait: 60000     # 最大等待时间(毫秒)
    test-while-idle: true
    test-on-borrow: false # 获取连接时测试是否可用
    test-on-return: false
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 20
    min-evictable-idle-time-millis: 300000
  session:
    store-type: redis
  resources:
    static-locations: ["/static/"]
  jackson:
    date-format: dd/MM/yy HH:mm:ss
    time-zone: GMT+8
  devtools:
    restart:
      #热部署生效
      enabled: false

mybatis:
  type-aliases-package: com.mtr.sscp.entity
  mapper-locations: classpath:mapper/*.xml
#  驼峰命名规范，不加不能把tap_time映射为tapTime字段实体
  configuration:
    map-underscore-to-camel-case: true

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false




#jdbc操作日志
log:
  jdbc:
    ps:
      executableSql: true
    rs:
      header: true

# /swagger-ui.html swagger访问网址
swagger:
  enable: true

#分布式id机器码      
snowflake:
  workerId: 6  #取值0-31
  datacenterId: 0  #取值0-31

