apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: zookeeper
    release: prometheus-operator
  name: zookeeper
  namespace: monitoring
spec:
  endpoints:
  - interval: 15s
    path: /metrics
    port: jmxxp
    scheme: http
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: zookeeper
      release: kafka
